language: rust
rust:
 - stable
 - beta
 - nightly
dist: bionic
addons:
  apt:
    packages:
    - firefox
    - chromium-browser
    - chromium-chromedriver
# XXX: https://packages.ubuntu.com/bionic/firefoxdriver
before_install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
before_script:
 - chromedriver --verbose > chromedriver.log 2>&1 &
 - geckodriver -v > geckodriver.log 2>&1 &
after_failure:
 - cat chromedriver.log
 - cat geckodriver.log
script:
 - cargo build --verbose
 - cargo test --verbose
matrix:
  allow_failures:
  - rust: nightly
